### ISSUE TITLE
Ubuntu Touch: Upload any type of file

### ISSUE THREAD

**Issue by bhdouglass** [fredldotme/harbour-owncloud#32]
Currently when running Ghost Cloud on Ubuntu Touch, tapping the "Upload file..." button opens the Gallery app to upload photos. I would like to be able to choose any type of file to upload (potentially via the file manager or the gallery app).

**Comment by fredldotme** [comment]
This is something I was investigating but for some odd reason setting the content type to `All` fails to show a working picker. I'm still wondering what's up with that.

**Comment by bhdouglass** [comment]
That's interesting. I'm not sure what's up with that, but alternatively you could make GhostCloud a destination for all file types and then I could export from the file manager to GhostCloud. Not as good as picking the file from within the app, but it would work around the issue.

**Comment by fredldotme** [comment]
Returning to the issue with `ContentType.All`, the error I get when calling `ContentPeer.request()` is:
`Unknown source for type: -1`

Also, Gallery is the only application currently capable of serving such a content picker source.

**Comment by fredldotme** [comment]
Solved similar to how GearBoy does it using a ContentPeerModel and hardcoding the file manager as a peer source. This will be in the next release.

**Comment by bhdouglass** [comment]
Awesome!
