### ISSUE TITLE
[UI] Elements on account list not high enough

### ISSUE THREAD

**Issue by null-von-sushi** [fredldotme/harbour-owncloud#33]
The highlighted item does not highlight the whole item with word wrapping if that makes sense. This also affects the tap-and-hold menu. I attached a picture, it should explain things better then I can.

![photo_2019-06-04_18-08-07](https://user-images.githubusercontent.com/13616397/58899070-efcee780-86f3-11e9-8d27-5be642d8826a.jpg)

Not sure if this applies to your app, and sorry if this is dumb (I just started learning QML), but I fixed this issue in my own project by setting the contentHeight of my ListItem to be the same as the height of the lable within said ListItem. So basically  `contentHeight: myLabelID.height`. That said, I am not even sure you use a list, just wanted to help :D

Just wanted to report it. Thanks for the app by the way!

**Comment by fredldotme** [comment]
Text elides now. Closed.
