### ISSUE TITLE
Where do files download to in Ubuntu Touch?

### ISSUE THREAD

**Issue by 3arn0wl** [fredldotme/harbour-owncloud#36]
Hi
I love this app: it's really straightforward to log into Nextcloud.

When I click on a file, it gives me options to Open or Download. However, when I press the Download button, there is no evidence that the file has been downloaded.

**Comment by fredldotme** [comment]
Hello! Which OS are you running GhostCloud on?

**Comment by 3arn0wl** [comment]
Hello! Thank you for getting back to me. I'm on the latest version of the Developer channel of Ubuntu Touch. (Not the Edge channel)

**Comment by fredldotme** [comment]
Then they are downloaded to `/home/phablet/.local/share/me.fredl.ghostcloud`.

**Comment by 3arn0wl** [comment]
Thank you
