### ISSUE TITLE
Compatibitly issue with NextCloud integration from jolla (SFOS 3.3.0.16)

### ISSUE THREAD

**Issue by Karry** [fredldotme/harbour-owncloud#44]
Hi. 

It seems that transferengine plugin is causing crashes of transferengine service ( /usr/bin/nemo-transfer-engine ) in latest SFOS (3.3.0.16). Probable cause it that new NextCloud plugin from Jolla is using the same symbols. 

```
[root@Sailfish ~]# objdump -C  --dynamic-syms /usr/lib/nemo-transferengine/plugins/libowncloudshareplugin.so | grep NextcloudUploader::~NextcloudUploader
00005910 g    DF .text  00000012  Base        NextcloudUploader::~NextcloudUploader()
000058dc g    DF .text  00000034  Base        NextcloudUploader::~NextcloudUploader()
000058dc g    DF .text  00000034  Base        NextcloudUploader::~NextcloudUploader()
[root@Sailfish ~]# 
[root@Sailfish ~]# objdump -C  --dynamic-syms /usr/lib/nemo-transferengine/plugins/libnextcloudshareplugin.so | grep NextcloudUploader::~NextcloudUploader
00015304 g    DF .text  00000014  Base        NextcloudUploader::~NextcloudUploader()
00014ffc g    DF .text  00000308  Base        NextcloudUploader::~NextcloudUploader()
00014ffc g    DF .text  00000308  Base        NextcloudUploader::~NextcloudUploader()
```
See thread here: https://together.jolla.com/question/226721/nemo-transfer-engine-is-crashing-sfos-33016/?answer=226730#post-id-226730
and original discussion in Qr Share plugin here: https://github.com/monich/sailfish-qrshare/issues/13

Beside obvious question - how to fix it (we may move GhostCloud classes to separate namespace), I have another one - are you original author of classes in `src/sharing` directory? It is licensed under terms of GPLv2, right? Symbols used NextCloud plugin from Jolla are interestingly similar. And package `transferengine-plugin-nextcloud` seems to be proprietary...

**Comment by fredldotme** [comment]
Thanks for bringing that up. I'll take a look at it over the coming week.

Yes, I'm the copyright holder of the GhostCloud-provided share plugin. What other symbols do match, could you provide more information?

**Comment by Karry** [comment]
I am paranoid probably :-) All public methods are defined by plugin interface and the fact that name of three classes match (NextcloudPluginInfo, NextcloudSharePlugin, NextcloudUploader) is not so big surprise... 

Full symbol list is here: https://gist.github.com/Karry/c38a88ab1df8861c0006a02adb541461

**Comment by fredldotme** [comment]
You are right. Though I have to admit, it would've been easier for everybody (assuming they just copied the interfaces straight from GhostCloud) that they renamed it properly. First come, first serve.

I'll analyze this the coming week.

**Comment by monich** [comment]
I think it's generally a good idea to compile plugins with `-fvisibility=hidden`, to avoid mix-up of symbols. If nothing else, that makes shared libraries smaller :) The top level object might still have to be renamed, though.

**Comment by fredldotme** [comment]
I'm currently hitting issues with SailfishOS SDK 3.1 where the required `nemotransferengine-qt5` devel package can't be found in the repos, causing the build to fail early on and not being able to package the additionals. Until this is solved I cannot release an update which fixes the symbols clash.

**Comment by monich** [comment]
FWIW this is how I'm building mine:

https://build.merproject.org/package/show/home:slava/sailfish-qrshare

although my case is slightly more sophisticated - the goal was to build a plugin compatible with libnemotransferengine-qt5.so before and after the ABI break, hence runtime detection of transfer-engine version and other obscure stuff.

Official SDK doesn't really have to contain nemotransferengine-qt5 because it's not a supported public API. If that package was in earlier SDK versions, it could be included there by mistake :) I'm consciously building against ancient versions and that works nicely, newer releases are backward compatible with older ones but not the other way around, which from my point of view makes old SDKs better than the new ones.

**Comment by fredldotme** [comment]
Yeah, it wasn't intended for the official SDK but having it install on-demand sure used to be a good feature, this feels like a step back in some ways. I was intentionally targeting the newer SDK as I was bitten by ABI breakage in the past. I hope the transferengine ABI stays the same for some time.

Anyways, I'll try again with an older target and see if the web interface allows me to install the devel package there. Thanks for the hints about the build service, not sure if my old porters account is active there.

**Comment by monich** [comment]
OBS that I just advertized can actually be shut down at any time (AFAIK primarily for legal reasons), don't invest too much time into it. I've just been using it from the very beginning, to build packages from scratch in a reliably reproducible way.

**Comment by Karry** [comment]
simple fix is merged to master, closing this issue...
