### ISSUE TITLE
Linux desktop version fails to compile, can't find "icons/theme/index.theme"

### ISSUE THREAD

**Issue by PureTryOut** [fredldotme/harbour-owncloud#77]
I'm trying to build the plain QtQuickcontrols version for postmarketOS/Alpine Linux but am failing to do so due to the error in the title:

```
/usr/lib/qt5/bin/rcc -name qml-ui-set ../../3rdparty/qml-ui-set/qml-ui-set.qrc -o qrc_qml-ui-set.cpp
/usr/lib/qt5/bin/rcc -name qml qml.qrc -o qrc_qml.cpp
make[2]: *** No rule to make target 'icons/theme/index.theme', needed by 'qrc_theme.cpp'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/bart/Documents/Git/alpine/aports/testing/ghostcloud/src/harbour-owncloud-0.9.9.5/src/app'
make[1]: *** [Makefile:91: sub-app-make_first-ordered] Error 2
make[1]: Leaving directory '/home/bart/Documents/Git/alpine/aports/testing/ghostcloud/src/harbour-owncloud-0.9.9.5/src'
make: *** [Makefile:91: sub-src-make_first-ordered] Error 2
```

I can indeed not find that folder and file anywhere, not in this repo nor in the 3rdparty ones.

CC @fredldotme

**Comment by PureTryOut** [comment]
Actually never mind, it seems that's a symlink to another 3rdparty module that I just hadn't prepared yet. It would be nice if there were GitHub releases with vendored sources in them :sweat_smile: 

And in case of Breeze icons it would be even better to not directly link to their icons at all but instead just use string-based references and let the system figure it out from the user-configured icon theme.

**Comment by fredldotme** [comment]
Previous Qt5 releases didn't have that Icon theme functionality baked into them, a patch to get rid of the requirement of including Breeze itself would be appreciated. :)

**Comment by PureTryOut** [comment]
Well there is atm a huge discussion going on between KDE and GNOME on what to do with icon themes on the Linux desktop actually. GNOME wants to get rid of them entirely (and have the app ship their own icons all the time) and KDE wants to keep them (and have the app rely on a system icon theme being installed that provides the icons as defined in the Freedesktop.org icon theme spec).

It's probably better to wait for some sort of result out of that, because it'll basically decide if it's better to rely on a system icon theme or let the app ship it's own icons.
